version: '3.7'
services:
  api-dev:
    container_name: core-bank
    restart: always
    build:
      context: .
      target: production
    env_file: .env.dev
    ports:
      - 3000:3000
    depends_on:
      - postgres-dev

  postgres-dev:
    container_name: postgres
    image: postgres:14
    restart: always
    env_file: .env.dev
    ports:
      - 5432:5432

  pgAdmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: luis@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-dev
