version: '3.7'
services:
  api-dev:
    container_name: core-bank
    build:
      context: .
      target: development
    volumes:
      - .:/home/node
      - /home/node/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres-dev
    command: npm run start:dev
    env_file:
      - .env.dev

  postgres-dev:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: